-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#181115',
  base01 = '#130c0f',
  base02 = '#211a1d',
  base03 = '#504349',
  base04 = '#d4c2c8',
  base05 = '#eddfe3',
  base06 = '#372e32',
  base07 = '#40373a',

  base08 = '#ffb4ab',
  base09 = '#f3ba9b',
  base0A = '#dfbdcc',
  base0B = '#fbb0d7',
  base0C = '#643d26',
  base0D = '#f3ba9b',
  base0E = '#fcd9e8',
  base0F = '#93000a',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#6c3454',
  fg = '#181115',
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#9c8d93',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#f3ba9b',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#dfbdcc',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#874b6c',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#130c0f',
  fg = '#fbb0d7',
})
